package edu.uga.cs.project4_geography_quiz;

import java.util.ArrayList;
import java.util.Arrays;

public class localLists {

    // I know this is very ugly but I needed to have some way to access the data while attempting to read from the database is causing app crashes

    public ArrayList<String> listOfCountries = new ArrayList<>(Arrays.asList(
            "Afghanistan" ,
            "Albania" ,
            "Algeria" ,
            "Andorra" ,
            "Angola" ,
            "Antigua and Barbuda" ,
            "Argentina" ,
            "Armenia" ,
            "Australia" ,
            "Austria" ,
            "Azerbaijan" ,
            "Bahrain" ,
            "Bangladesh" ,
            "Barbados" ,
            "Belarus" ,
            "Belgium" ,
            "Belize" ,
            "Benin" ,
            "Bhutan" ,
            "Bolivia" ,
            "Bosnia and Herzegovina" ,
            "Botswana" ,
            "Brazil" ,
            "Brunei" ,
            "Bulgaria" ,
            "Burkina Faso" ,
            "Burundi" ,
            "Cambodia" ,
            "Cameroon" ,
            "Canada" ,
            "Cape Verde" ,
            "Central African Republic" ,
            "Chad" ,
            "Chile" ,
            "China" ,
            "Colombia" ,
            "Comoros" ,
            "Congo" ,
            "Costa Rica" ,
            "Croatia" ,
            "Cuba" ,
            "Cyprus" ,
            "Czech Republic" ,
            "Democratic Republic of the Congo" ,
            "Denmark" ,
            "Djibouti" ,
            "Dominica" ,
            "Dominican Republic" ,
            "East Timor" ,
            "Ecuador" ,
            "Egypt" ,
            "El Salvador" ,
            "Equatorial Guinea" ,
            "Eritrea" ,
            "Estonia" ,
            "Ethiopia" ,
            "Fiji" ,
            "Finland" ,
            "France" ,
            "Gabon" ,
            "Gambia" ,
            "Georgia" ,
            "Germany" ,
            "Ghana" ,
            "Greece" ,
            "Grenada" ,
            "Guatemala" ,
            "Guinea" ,
            "Guinea-Bissau" ,
            "Guyana" ,
            "Haiti" ,
            "Honduras" ,
            "Hungary" ,
            "Iceland" ,
            "India" ,
            "Indonesia" ,
            "Iran" ,
            "Iraq" ,
            "Ireland" ,
            "Israel" ,
            "Italy" ,
            "Ivory Coast" ,
            "Jamaica" ,
            "Japan" ,
            "Jordan" ,
            "Kazakhstan" ,
            "Kenya" ,
            "Kiribati" ,
            "Kosovo" ,
            "Kuwait" ,
            "Kyrgyzstan" ,
            "Laos" ,
            "Latvia" ,
            "Lebanon" ,
            "Lesotho" ,
            "Liberia" ,
            "Libya" ,
            "Liechtenstein" ,
            "Lithuania" ,
            "Luxembourg" ,
            "Macedonia" ,
            "Madagascar" ,
            "Malawi" ,
            "Malaysia" ,
            "Maldives" ,
            "Mali" ,
            "Malta" ,
            "Marshall Islands" ,
            "Mauritania" ,
            "Mauritius" ,
            "Mexico" ,
            "Micronesia" ,
            "Moldova" ,
            "Monaco" ,
            "Mongolia" ,
            "Montenegro" ,
            "Morocco" ,
            "Mozambique" ,
            "Myanmar" ,
            "Namibia" ,
            "Nauru" ,
            "Nepal" ,
            "Netherlands" ,
            "New Zealand" ,
            "Nicaragua" ,
            "Niger" ,
            "Nigeria" ,
            "North Korea" ,
            "Norway" ,
            "Oman" ,
            "Pakistan" ,
            "Palau" ,
            "Panama" ,
            "Papua New Guinea" ,
            "Paraguay" ,
            "Peru" ,
            "Philippines" ,
            "Poland" ,
            "Portugal" ,
            "Qatar" ,
            "Romania" ,
            "Russia" ,
            "Rwanda" ,
            "Saint Kitts and Nevis" ,
            "Saint Lucia" ,
            "Saint Vincent and the Grenadines" ,
            "Samoa" ,
            "San Marino" ,
            "Sao Tome and Principe" ,
            "Saudi Arabia" ,
            "Senegal" ,
            "Serbia" ,
            "Seychelles" ,
            "Sierra Leone" ,
            "Singapore" ,
            "Slovakia" ,
            "Slovenia" ,
            "Solomon Islands" ,
            "Somalia" ,
            "South Africa" ,
            "South Korea" ,
            "South Sudan" ,
            "Spain" ,
            "Sri Lanka" ,
            "Sudan" ,
            "Suriname" ,
            "Swaziland" ,
            "Sweden" ,
            "Switzerland" ,
            "Syria" ,
            "Taiwan" ,
            "Tajikistan" ,
            "Tanzania" ,
            "Thailand" ,
            "Togo" ,
            "Tonga" ,
            "Trinidad and Tobago" ,
            "Tunisia" ,
            "Turkey" ,
            "Turkmenistan" ,
            "Tuvalu" ,
            "Uganda" ,
            "Ukraine" ,
            "United Arab Emirates" ,
            "United Kingdom" ,
            "United States of America" ,
            "Uruguay" ,
            "Uzbekistan" ,
            "Vanuatu" ,
            "Vatican City" ,
            "Venezuela" ,
            "Vietnam" ,
            "Yemen" ,
            "Zambia" ,
            "Zimbabwe"
    ));


   public ArrayList<String> listOfContinents = new ArrayList<>(Arrays.asList(
            "Asia" ,
            "Europe" ,
            "Africa" ,
            "Europe" ,
            "Africa" ,
            "North America" ,
            "South America" ,
            "Europe" ,
            "Oceania" ,
            "Europe" ,
            "Europe" ,
            "Asia" ,
            "Asia" ,
            "North America" ,
            "Europe" ,
            "Europe" ,
            "North America" ,
            "Africa" ,
            "Asia" ,
            "South America" ,
            "Europe" ,
            "Africa" ,
            "South America" ,
            "Asia" ,
            "Europe" ,
            "Africa" ,
            "Africa" ,
            "Asia" ,
            "Africa" ,
            "North America" ,
            "Africa" ,
            "Africa" ,
            "Africa" ,
            "South America" ,
            "Asia" ,
            "South America" ,
            "Africa" ,
            "Africa" ,
            "North America" ,
            "Europe" ,
            "North America" ,
            "Europe" ,
            "Europe" ,
            "Africa" ,
            "Europe" ,
            "Africa" ,
            "North America" ,
            "North America" ,
            "Asia" ,
            "South America" ,
            "Africa" ,
            "North America" ,
            "Africa" ,
            "Africa" ,
            "Europe" ,
            "Africa" ,
            "Oceania" ,
            "Europe" ,
            "Europe" ,
            "Africa" ,
            "Africa" ,
            "Europe" ,
            "Europe" ,
            "Africa" ,
            "Europe" ,
            "North America" ,
            "North America" ,
            "Africa" ,
            "Africa" ,
            "South America" ,
            "North America" ,
            "North America" ,
            "Europe" ,
            "Europe" ,
            "Asia" ,
            "Asia" ,
            "Asia" ,
            "Asia" ,
            "Europe" ,
            "Asia" ,
            "Europe" ,
            "Africa" ,
            "North America" ,
            "Asia" ,
            "Asia" ,
            "Asia" ,
            "Africa" ,
            "Oceania" ,
            "Europe" ,
            "Asia" ,
            "Asia" ,
            "Asia" ,
            "Europe" ,
            "Asia" ,
            "Africa" ,
            "Africa" ,
            "Africa" ,
            "Europe" ,
            "Europe" ,
            "Europe" ,
            "Europe" ,
            "Africa" ,
            "Africa" ,
            "Asia" ,
            "Asia" ,
            "Africa" ,
            "Europe" ,
            "Oceania" ,
            "Africa" ,
            "Africa" ,
            "North America" ,
            "Oceania" ,
            "Europe" ,
            "Europe" ,
            "Asia" ,
            "Europe" ,
            "Africa" ,
            "Africa" ,
            "Asia" ,
            "Africa" ,
            "Oceania" ,
            "Asia" ,
            "Europe" ,
            "Oceania" ,
            "North America" ,
            "Africa" ,
            "Africa" ,
            "Asia" ,
            "Europe" ,
            "Asia" ,
            "Asia" ,
            "Oceania" ,
            "North America" ,
            "Oceania" ,
            "South America" ,
            "South America" ,
            "Asia" ,
            "Europe" ,
            "Europe" ,
            "Asia" ,
            "Europe" ,
            "Asia" ,
            "Africa" ,
            "North America" ,
            "North America" ,
            "North America" ,
            "Oceania" ,
            "Europe" ,
            "Africa" ,
            "Asia" ,
            "Africa" ,
            "Europe" ,
            "Africa" ,
            "Africa" ,
            "Asia" ,
            "Europe" ,
            "Europe" ,
            "Oceania" ,
            "Africa" ,
            "Africa" ,
            "Asia" ,
            "Africa" ,
            "Europe" ,
            "Asia" ,
            "Africa" ,
            "South America" ,
            "Africa" ,
            "Europe" ,
            "Europe" ,
            "Asia" ,
            "Asia" ,
            "Asia" ,
            "Africa" ,
            "Asia" ,
            "Africa" ,
            "Oceania" ,
            "North America" ,
            "Africa" ,
            "Asia" ,
            "Asia" ,
            "Oceania" ,
            "Africa" ,
            "Europe" ,
            "Asia" ,
            "Europe" ,
            "North America" ,
            "South America" ,
            "Asia" ,
            "Oceania" ,
            "Europe" ,
            "South America" ,
            "Asia" ,
            "Asia" ,
            "Africa" ,
            "Africa"
   ));



}
